version: "3"
services:
  web:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/html
    networks:
      - nginxphp

  php:
    image: php:fpm
    expose:
      - 9000
    volumes:
      - ./html:/var/html
    networks:
      - nginxphp

networks:
  nginxphp:
